# Generated by Django 6.0.1 on 2026-01-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('business', 'Business'), ('entertainment', 'Entertainment'), ('health', 'Health')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='profile_link',
            new_name='author_url',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_link',
        ),
        migrations.AddField(
            model_name='publication',
            name='fingerprints',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_url',
            field=models.URLField(default='', max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
