# Generated by Django 6.0.1 on 2026-01-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_classifieddocument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlerlog',
            old_name='publications_found',
            new_name='documents_added',
        ),
    ]
