# Generated by Django 6.0.1 on 2026-01-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_rename_publications_found_crawlerlog_documents_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='author_url',
            new_name='profile_link',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_url',
            new_name='publication_link',
        ),
    ]
