# Generated by Django 6.0.1 on 2026-01-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_rename_author_url_publication_profile_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
