# Generated by Django 6.0.1 on 2026-01-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0005_publication_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='category',
        ),
    ]
